### ISSUE TITLE
SafariNet Crash

### ISSUE THREAD

**Issue by winstliu** [powercrystals/MineFactoryReloaded#29]
First time I've seen this (other than outdated IC2 crashes), so I have no idea how to fix it.  Worked fine with 2.1.2.
Mods of interest:  BC (from Github), IC2 build 220, Thermal Expansion.  Forge .627, Optifine D3 preview.  Powercrystal's Core 1.0.2.22 (in coremods folder) and MFR 2.1.4.48.

`2013-02-20 17:33:19 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2013-02-20 17:33:19 [SEVERE] [ForgeModLoader] Caught exception from MFReloaded
java.lang.NoSuchMethodError: powercrystals.minefactoryreloaded.api.FarmingRegistry.registerSafariNetHandler(Lpowercrystals/minefactoryreloaded/api/ISafariNetHandler;)V
    at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.registerFarmables(MineFactoryReloadedCore.java:579)
    at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.load(MineFactoryReloadedCore.java:417)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:676)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:207)
    at net.minecraft.client.Minecraft.a(Minecraft.java:456)
    at asq.a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:744)
    at java.lang.Thread.run(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR] cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: powercrystals.minefactoryreloaded.api.FarmingRegistry.registerSafariNetHandler(Lpowercrystals/minefactoryreloaded/api/ISafariNetHandler;)V
2013-02-20 17:33:29 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.transition(LoadController.java:130)
2013-02-20 17:33:29 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.initializeMods(Loader.java:677)
2013-02-20 17:33:29 [INFO] [STDERR]     at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:207)
2013-02-20 17:33:29 [INFO] [STDERR]     at net.minecraft.client.Minecraft.a(Minecraft.java:456)
2013-02-20 17:33:29 [INFO] [STDERR]     at asq.a(SourceFile:56)
2013-02-20 17:33:29 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:744)
2013-02-20 17:33:29 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR] Caused by: java.lang.NoSuchMethodError: powercrystals.minefactoryreloaded.api.FarmingRegistry.registerSafariNetHandler(Lpowercrystals/minefactoryreloaded/api/ISafariNetHandler;)V
2013-02-20 17:33:29 [INFO] [STDERR]     at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.registerFarmables(MineFactoryReloadedCore.java:579)
2013-02-20 17:33:29 [INFO] [STDERR]     at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.load(MineFactoryReloadedCore.java:417)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-02-20 17:33:29 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-02-20 17:33:29 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-02-20 17:33:29 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
2013-02-20 17:33:29 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.initializeMods(Loader.java:676)
2013-02-20 17:33:29 [INFO] [STDERR]     ... 5 more`

**Comment by powercrystals** [comment]
Apologies, I only just saw this. Somehow it's not properly loading the API - make sure nobody else is including the MFR API to start with (Plugins for Forestry does, I believe).

**Comment by winstliu** [comment]
Well, yes, I have PfF.  I'll report back when I play MC again (prob. tomorrow).
Shouldn't there be a PfF reference in the stacktrace though?

**Comment by powercrystals** [comment]
What's happening is PfF is overwriting my classes in memory because it's loading second, but they're still my classes so you see my class names. It's pretty hard for you as the user to to figure that out unless you know to look for it.

**Comment by winstliu** [comment]
Ah, ok.  I'll move it out of my mods folder tomorrow and see.  Thanks :smile:

**Comment by winstliu** [comment]
Fixed, thank you.  I'll create an issue at PfF's Github page.
